### ISSUE TITLE
Problem: spec behaviours not directly expressed in test suites

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#676]
e.g. https://github.com/crypto-org-chain/chain-main/blob/0f99b253887b4bcce0dac2fd65635fb07c00920b/x/nft/keeper/keeper_test.go#L52

it may be worth switching to https://github.com/onsi/ginkgo

**Comment by christianlantin** [comment]
Done

**Comment by afa-farkhod** [comment]
hey there, is the current issue still active? if so can I get assigned, happy to contribute, thanks
